# Generated by Django 5.1.3 on 2024-11-10 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honeycheckerservice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HoneyChecker',
            new_name='HoneyCheckerTable',
        ),
    ]
